In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import os
import sys

print("at directory:", os.getcwd())
print("changing to root directory")
os.chdir("..")
print("at directory:", os.getcwd())

at directory: /Users/wilka/git/research/human-dyna-web/analysis_notebooks
changing to root directory
at directory: /Users/wilka/git/research/human-dyna-web

In [4]:
import glob

print("at directory:", os.getcwd())

glob.glob("keys/*")

at directory: /Users/wilka/git/research/human-dyna-web

['keys/datastore-key.json']

In [5]:
# ON COMPUTER
RESULTS_DIR = "/Users/wilka/git/research/"
USER_RESULTS_DIR = os.path.join(RESULTS_DIR, "results/human_dyna/user_data/exps")

In [6]:
# from analysis import housemaze_download_data
from analysis.download_user_data import download_user_files

bucket_name = "human-dyna"
bucket_prefix = "data/"
# pattern = "data/data_user=*_name=r0-v2*debug=0.json"
# human_data_pattern = "v2*shortcut*debug-2"
# human_data_pattern = "pilot*plan*"
human_data_pattern = "final*v2*"

download_user_files(
  bucket_name=bucket_name,
  prefix=bucket_prefix,
  pattern=f"data/*user=*{human_data_pattern}*",
  destination_folder=USER_RESULTS_DIR,
)

In [16]:
from glob import glob

files = f"{USER_RESULTS_DIR}/*{human_data_pattern}*.json"
files = f"{USER_RESULTS_DIR}/*path*.json"
# files = 'jaxemaze_data/*.json'
valid_files = list(set(glob(files)))
len(valid_files)

139

In [17]:
from pprint import pprint
import json
from nicewebrl.utils import read_all_records_sync

nfinished = 0
for idx, file in enumerate(valid_files):
  try:
    data = read_all_records_sync(file)
  except Exception as e:
    print("-" * 25)
    print(idx, os.path.basename(file))
    print(e)
    continue
  if len(data) < 2:
    print(f"{file} has length = {len(data)}")
    continue
  finished = data[-1].get("finished", False)
  if finished:
    print
    nfinished += 1
    print("-" * 25)
    print(idx, os.path.basename(file))
    print("\n" + data[-1]["feedback"] or "N/A")
    # print('bonus:', data[-1]['bonus'])
    # print("feedback:")
    if "feedback" in data[-2]["data"]:
      pprint(data[-2]["data"])
  break

-------------------------
0 user=1170879615_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json

In [18]:
# import nicewebrl

# # file = '/Users/wilka/git/research/results/human_dyna/user_data/exp4/data_user=1844620330_name=exp4-v1-r1-t0-plan_exp=4_debug=0.json'
# # file = "/Users/wilka/git/research/results/human_dyna//user_data/exp4/data_user=708665372_name=exp4-v1-r0-t0-plan_exp=4_debug=0.json"

# data = nicewebrl.read_all_records(file, synchronous=True)

In [19]:
# data[0]["data"].keys(), data[-2]["data"].keys()

In [20]:
import jax
from experiment_utils import SuccessTrackingAutoResetWrapper
from analysis.housemaze_user_data import (
  make_env_params,
  task_objects,
  make_episode_data,
)
from housemaze.human_dyna import multitask_env
from housemaze.human_dyna import web_env
from housemaze.human_dyna import mazes

################
# Setup environment
################
dummy_rng = jax.random.PRNGKey(42)
dummy_env_params = make_env_params(mazes.big_practice_maze)
task_runner = multitask_env.TaskRunner(task_objects=task_objects)
base_env = web_env.HouseMaze(
  task_runner=task_runner,
  num_categories=200,
)
end = SuccessTrackingAutoResetWrapper(base_env)
example_web_timestep = end.reset(dummy_rng, dummy_env_params)

In [21]:
# TESTING
df, data = make_episode_data(
  file=file,
  example_timestep=example_web_timestep,
  overwrite_episode_info=True,
  require_finished=False,
)
df.head()

shape: (5, 34)
┌───────┬─────────────┬───────────┬─────────────┬───┬────────────┬────────────┬────────────┬───────┐
│ index ┆ maze        ┆ condition ┆ name        ┆ … ┆ log_max_en ┆ log_max_fi ┆ optimal_le ┆ reuse │
│ ---   ┆ ---         ┆ ---       ┆ ---         ┆   ┆ d_rt       ┆ nal_rt     ┆ ngth_devia ┆ ---   │
│ u32   ┆ str         ┆ i64       ┆ str         ┆   ┆ ---        ┆ ---        ┆ nce        ┆ i32   │
│       ┆             ┆           ┆             ┆   ┆ f32        ┆ f32        ┆ ---        ┆       │
│       ┆             ┆           ┆             ┆   ┆            ┆            ┆ i64        ┆       │
╞═══════╪═════════════╪═══════════╪═════════════╪═══╪════════════╪════════════╪════════════╪═══════╡
│ 0     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -1.327988  ┆ -0.794051  ┆ 152        ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 1     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -1.406456  ┆ -1.406456  ┆ 2          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 2     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -1.24476   ┆ -1.24476   ┆ 0          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 3     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -1.509547  ┆ -1.435443  ┆ 1          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 4     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -1.366452  ┆ -1.366452  ┆ 2          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
└───────┴─────────────┴───────────┴─────────────┴───┴────────────┴────────────┴────────────┴───────┘

In [22]:
df['reuse'].unique()

shape: (3,)
Series: 'reuse' [i32]
[
	null
	0
	1
]