In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
import sys

print("at directory:", os.getcwd())
print("changing to root directory")
os.chdir("..")
print("at directory:", os.getcwd())

at directory: /Users/wilka/git/research/human-dyna-web/analysis_notebooks
changing to root directory
at directory: /Users/wilka/git/research/human-dyna-web

In [3]:
import glob

print("at directory:", os.getcwd())

glob.glob("keys/*")

at directory: /Users/wilka/git/research/human-dyna-web

['keys/datastore-key.json']

In [4]:
# ON COMPUTER
RESULTS_DIR = "/Users/wilka/git/research/"
USER_RESULTS_DIR = os.path.join(RESULTS_DIR, "results/human_dyna/user_data/exps")

In [5]:
# from analysis import housemaze_download_data
from analysis.download_user_data import download_user_files

bucket_name = "human-dyna"
bucket_prefix = "data/"
# pattern = "data/data_user=*_name=r0-v2*debug=0.json"
# human_data_pattern = "v2*shortcut*debug-2"
# human_data_pattern = "pilot*plan*"
human_data_pattern = "final*v2*"

download_user_files(
  bucket_name=bucket_name,
  prefix=bucket_prefix,
  pattern=f"data/*user=*{human_data_pattern}*",
  destination_folder=USER_RESULTS_DIR,
)

File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1001779639_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1008223757_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1017609201_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1047131165_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1052354210_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1064468626_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1064862666_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1078799027_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1082264822_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1089753231_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1095744071_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1117852266_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1127059973_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1128634868_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1142580542_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1149736083_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1151657091_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1156039573_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1170879615_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1186517209_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1193893833_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1221712759_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1243974084_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1244686810_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1247187330_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1249329302_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1253454766_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1256189089_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1258658118_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1265379104_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1279392686_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1284678002_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1307077322_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1307313921_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1313889079_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1318052322_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1318536171_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1328145108_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1331031463_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1335679548_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1336457954_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1342993665_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1375199282_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1394568166_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1401401237_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1414111605_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1420648530_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1421347227_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1435122045_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1450505575_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=145383710_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=14583402_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1469191355_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=147461176_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1483000009_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1493943718_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1506559481_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1508932411_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1523262937_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1540976407_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1547584979_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=155600137_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1564299030_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=156559091_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1572701369_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1579131812_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1580376282_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1588331262_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=159473847_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1595262541_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1608921724_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1691523912_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1694893673_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1698421238_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1711720583_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1712015234_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1728215748_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1730562501_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1737924509_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1748213514_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1753322626_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1758345214_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1764885867_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1765360315_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1775725987_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1782349929_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1796497806_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1811957609_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1812687595_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1813245517_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1817266936_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1827707662_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1849329418_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1849696965_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1850933526_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1866371705_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=18824410_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1900242051_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=190203667_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1903749834_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=193687558_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1939552411_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1940375115_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1950197649_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1952847534_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1959819693_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1969213735_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1977408126_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1986422916_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1987556364_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1989068362_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2010719549_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2018750717_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2034746408_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2042078739_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2075111284_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2092627220_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2095786591_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2098905507_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2099451657_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2101454290_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2103777251_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=210850856_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2112734708_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2115915525_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2132464486_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2135416613_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=214713682_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2151238155_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2156816959_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2195407025_name=jaxmaze_final-v2-r0-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2198559889_name=jaxmaze_final-v2-r1-t0-shortcut_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=223001226_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2248040896_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=22557756_name=jaxmaze_final-v2-r1-t0-plan_debug=0.json
File already exists:
	 /Users/wilka/git/research/results/human_dyna/user_data/exps/user=2281217786_name=jaxmaze_final-v2-r1-t0-start_debug=0.json
File already exists:

In [6]:
from glob import glob

files = f"{USER_RESULTS_DIR}/*{human_data_pattern}*.json"
files = f"{USER_RESULTS_DIR}/*path*.json"
# files = 'jaxemaze_data/*.json'
valid_files = list(set(glob(files)))
len(valid_files)

139

In [7]:
from pprint import pprint
import json
from nicewebrl.utils import read_all_records_sync

nfinished = 0
for idx, file in enumerate(valid_files):
  try:
    data = read_all_records_sync(file)
  except Exception as e:
    print("-" * 25)
    print(idx, os.path.basename(file))
    print(e)
    continue
  if len(data) < 2:
    print(f"{file} has length = {len(data)}")
    continue
  finished = data[-1].get("finished", False)
  if finished:
    print
    nfinished += 1
    print("-" * 25)
    print(idx, os.path.basename(file))
    print("\n" + data[-1]["feedback"] or "N/A")
    # print('bonus:', data[-1]['bonus'])
    # print("feedback:")
    if "feedback" in data[-2]["data"]:
      pprint(data[-2]["data"])
  break

Incomplete record in /Users/wilka/git/research/results/human_dyna/user_data/exps/user=1113634923_name=exp5-v2-r0-t0-paths_debug=0.json

/Users/wilka/git/research/results/human_dyna/user_data/exps/user=1113634923_name=exp5-v2-r0-t0-paths_debug=0.json has length = 0
-------------------------
1 user=3109174614_name=jaxmaze_final-v2-r1-t0-paths_debug=0.json

The experiement went fine

In [9]:
# data[-1]

In [8]:
# import nicewebrl

# # file = '/Users/wilka/git/research/results/human_dyna/user_data/exp4/data_user=1844620330_name=exp4-v1-r1-t0-plan_exp=4_debug=0.json'
# # file = "/Users/wilka/git/research/results/human_dyna//user_data/exp4/data_user=708665372_name=exp4-v1-r0-t0-plan_exp=4_debug=0.json"

# data = nicewebrl.read_all_records(file, synchronous=True)

In [19]:
# data[0]["data"].keys(), data[-2]["data"].keys()

In [10]:
import jax
from experiment_utils import SuccessTrackingAutoResetWrapper
from analysis.housemaze_user_data import (
  make_env_params,
  task_objects,
  make_episode_data,
)
from housemaze.human_dyna import multitask_env
from housemaze.human_dyna import web_env
from housemaze.human_dyna import mazes

################
# Setup environment
################
dummy_rng = jax.random.PRNGKey(42)
dummy_env_params = make_env_params(mazes.big_practice_maze)
task_runner = multitask_env.TaskRunner(task_objects=task_objects)
base_env = web_env.HouseMaze(
  task_runner=task_runner,
  num_categories=200,
)
end = SuccessTrackingAutoResetWrapper(base_env)
example_web_timestep = end.reset(dummy_rng, dummy_env_params)

No file specified for image dict.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/image_data.pkl

In [13]:
# TESTING
df, data = make_episode_data(
  file=file,
  example_timestep=example_web_timestep,
  overwrite_episode_info=True,
  require_finished=False,
)
df.head()

No file specified for image dict.
Using: /Users/wilka/git/research/human-dyna-web/libraries/housemaze/housemaze/image_data.pkl

shape: (5, 40)
┌───────┬─────────────┬───────────┬─────────────┬───┬────────────┬────────────┬────────────┬───────┐
│ index ┆ maze        ┆ condition ┆ name        ┆ … ┆ log_max_en ┆ log_max_fi ┆ optimal_le ┆ reuse │
│ ---   ┆ ---         ┆ ---       ┆ ---         ┆   ┆ d_rt       ┆ nal_rt     ┆ ngth_devia ┆ ---   │
│ u32   ┆ str         ┆ i64       ┆ str         ┆   ┆ ---        ┆ ---        ┆ nce        ┆ i32   │
│       ┆             ┆           ┆             ┆   ┆ f32        ┆ f32        ┆ ---        ┆       │
│       ┆             ┆           ┆             ┆   ┆            ┆            ┆ i64        ┆       │
╞═══════╪═════════════╪═══════════╪═════════════╪═══╪════════════╪════════════╪════════════╪═══════╡
│ 0     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ 0.412116   ┆ 0.13803    ┆ 1          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 1     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -0.921278  ┆ -0.921278  ┆ 9          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 2     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -0.857998  ┆ -0.857998  ┆ 3          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 3     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -1.207278  ┆ -1.002366  ┆ 9          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
│ 4     ┆ big_m3_maze ┆ 0         ┆ big_m3_maze ┆ … ┆ -1.016083  ┆ -0.857998  ┆ 4          ┆ null  │
│       ┆ 1_(F,F)     ┆           ┆ 1__(F,F)_ev ┆   ┆            ┆            ┆            ┆       │
│       ┆             ┆           ┆ al1         ┆   ┆            ┆            ┆            ┆       │
└───────┴─────────────┴───────────┴─────────────┴───┴────────────┴────────────┴────────────┴───────┘

In [22]:
df['reuse'].unique()

shape: (3,)
Series: 'reuse' [i32]
[
	null
	0
	1
]